# NumPy - Array Attributes Part-2

# numpy.sort()

In [6]:
import numpy as np
Y = np.array([6,10,3,4,5,6,7])

In [4]:
Y.sort()

# numpy.argmax() and numpy.argmin()

In [8]:
Y.argmin()

2

# numpy.where()   Filters

In [11]:
np.where(Y>4)

(array([0, 1, 4, 5, 6], dtype=int64),)

In [12]:
Y

array([ 6, 10,  3,  4,  5,  6,  7])

# Deep Copy ndarray.copy()


In [20]:
Y

array([18, 30,  9, 12, 15, 18, 21])

In [21]:
X = Y.copy()