# NumPy - Array Attributes Part-1 

## shape and reshape

In [5]:
import numpy as np
x = np.array([1,1,1,2,3,5])

In [15]:
x.reshape((3,2))

array([[1, 1],
       [1, 2],
       [3, 5]])

# Arange

In [10]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# Empty array

In [12]:
np.array([])

array([], dtype=float64)

# Array with zeros


In [13]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

# Array with ones

In [14]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

# Array from range

In [15]:
np.array(range(1,6))

array([1, 2, 3, 4, 5])

# Linespace

In [16]:
np.linspace(0,5,50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])