# NumPy - Linear Algebra

# numpy.linalg
dot product <br>
cross product <br>
determinant<br>
inv <br>
solve

In [1]:
import numpy as np

X = np.random.random_sample((3,3))
Y = np.random.random_sample((3,3))

In [3]:
X,Y

(array([[0.6765346 , 0.99793316, 0.69942841],
        [0.64447073, 0.71261442, 0.56126489],
        [0.75032435, 0.81149071, 0.51761701]]),
 array([[0.75771033, 0.54865105, 0.67737796],
        [0.33686967, 0.50588052, 0.46428786],
        [0.6349522 , 0.81529216, 0.99830706]]))

In [4]:
np.dot(X,Y)

array([[1.29289427, 1.44625486, 1.61984219],
       [1.08475669, 1.17168216, 1.32772319],
       [1.17055718, 1.24419268, 1.40175917]])

In [5]:
np.cross(X,Y)

array([[ 0.2922358 ,  0.07169451, -0.38496285],
       [ 0.04692524, -0.11014682,  0.08596701],
       [ 0.38810782, -0.42039204,  0.09647574]])

In [6]:
np.linalg.det(X)

0.020582675218410625

In [9]:
np.linalg.inv(X)

array([[  7.97034274,  12.32232009, -14.62822815],
       [  2.51766305,   7.42873119,  -6.66680761],
       [-11.72599596, -23.1487923 ,  25.90822692]])

In [7]:
# 5x+ 2y = 3
# 6x-5y = 4

X = np.array([[5,2],[6 ,-5 ]])
Y = np.array([3,4])

solution = np.linalg.solve(X,Y)


In [8]:
print(solution)

[ 0.62162162 -0.05405405]


In [9]:
6*solution[0]- 5* solution[1]

4.0

# Matrix eigenvalues Functions

Eignvalue --- eigh <br>
Eignvectors ---eig <br>
trace

In [11]:
np.linalg.eigh(X)

(array([-7.81024968,  7.81024968]), array([[ 0.4241554 , -0.90558942],
        [-0.90558942, -0.4241554 ]]))

### And a lot