In [1]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn import datasets
from sklearn import tree
import pandas as pd
import os

In [2]:
iris = datasets.load_iris()

In [3]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
input_data = pd.DataFrame(iris['data'],columns = ['sepal length (cm)',
                                                  'sepal width (cm)',
                                                  'petal length (cm)',
                                                  'petal width (cm)'])

In [8]:
input_data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [10]:
input_data['target'] = iris['target']

In [11]:
input_data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [7]:
input_data.iloc[:,4].head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int32

In [21]:
X_train, X_test, y_train, y_test = train_test_split(input_data.iloc[:,:4],
                                                    input_data.iloc[:,4], 
                                                    test_size=0.55,
                                                    random_state=42)

In [22]:
X_test.shape

(83, 4)

In [23]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [24]:
clf.predict(X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0,
       1, 2, 0, 1, 2, 0, 1, 2, 2, 1, 2, 1, 0, 1, 2, 0, 0])

In [25]:
y_test.values

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0,
       1, 2, 0, 1, 2, 0, 2, 2, 1, 1, 2, 1, 0, 1, 2, 0, 0])

In [32]:
import numpy as np
df1 =pd.DataFrame(np.vstack([clf.predict(X_test),y_test.values]).T,columns=['predicted','actuals'])

In [36]:
df1[df1['predicted']!=df1['actuals']]

predicted  actuals
8           2        1
46          1        2
59          2        1
72          1        2
74          2        1

In [26]:
confusion_matrix(clf.predict(X_test),y_test)

array([[32,  0,  0],
       [ 0, 23,  2],
       [ 0,  3, 23]], dtype=int64)